### ISSUE TITLE
Long loading time, but only with launcher

### ISSUE THREAD

**Issue by ThreeCrowDay** [bahusafoo/Atavism-Game-Launcher-for-Windows#4]
Hello. Every time I make a build of the game without the launcher to test a few things, it only takes me about five seconds to reach the login screen.

But when I use the launcher to enter the game, it consistently takes about 90 seconds to get to the login scene. What could be taking so long just to get to the login?

Crowsinger

**Comment by bahusafoo** [comment]
It is due to the validation scene being single threaded and working on a large list of large files.  The validation scene is still utilizing the first iteration ever created and hasn't had any enhancement focus given at all. 
 Presently, The bigger your game client, the worse this will be.  Validation is important, as it ensures your game clients don't have anything modded or extra added to them other than what you deliver.  There is a feature enhancement planned already for this that will make this way faster and display a status as validation occurs (currently, the process appears to become unresponsive as file validation happens on the main thread, multithreading will allow us to display a status indicator, at least a spinner).  Going to close this for now as a duplicate - https://github.com/bahusafoo/Atavism-Game-Launcher-for-Windows/issues/2
